@startuml
left to right direction

class Importer {
 +dicom(folder?: string, files?: string[]): np.ndarray
 +ibf(folder?: string, files?: string[]): np.ndarray
}

class Core {
 +pixel_array
 +pixel_spacing
 +slice_thickness
 +slice(axis: int, location: int): np.ndarray
 +chunk(dimensions: np.ndarray): np.ndarray
 +join(core: Core): void
 +filter(callback: (x: int) -> bool): void
 +volume(): void
 +shape(): void
}

class Analyze {
 +brightness_trace(slice: np.ndarray): np.ndarray
 +density_trace(slice: np.ndarray): np.ndarray
 +percent_density(range: [float, float]): int 
}

class Visualize {
 +brightness_graph(trace: np.ndarray): void
 +density_graph(trace: np.ndarray): void
 +slice(slice: np.ndarray): void
 +core(core: Core): void
}

Importer --> Core
Core --> Analyze
Analyze --> Visualize
@enduml