name: "Lint and Test"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "25-create-an-github-action-that-runs-the-tests" ]

permissions:
  contents: read

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Branch
      uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install Dependencies via Poetry
      run: poetry install
    - name: Run Tests via PyTest
      run: poetry run pytest
    - name: Lint Code with Ruff
      uses: chartboost/ruff-action@v1
