name: "Publish to PyPI"

on:
  push:
    branches:
      - main
      - 33-create-a-github-action-for-publishing-to-pypi

permissions:
  contents: read

jobs:
  pypi_publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Branch
      uses: actions/checkout@v4
    - name: Install Poetry
      run: pipx install poetry
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install Dependencies via Poetry
      run: poetry install
    - name: Add PyPI Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish Package
      run: poetry publish --build
