name: "Publish to PyPI"

on:
  push:
    branches:
      - main
      - 33-create-a-github-action-for-publishing-to-pypi

permissions:
  contents: read

jobs:
  pypi_publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Branch
      uses: actions/checkout@v4
    - name: Test Variable
      run: echo ${{ secrets.PYPI_API_TOKEN }}
