name: Runs Tests on Library

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "25-create-an-github-action-that-runs-the-tests" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Set Up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"