name: Runs Tests on Library

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "25-create-an-github-action-that-runs-the-tests" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Configure Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Python Dependencies via Poetry
      run: poetry install
    - name: Run Tests with PyTest
      run: pytest