name: "Verify Version Number"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "33-create-a-github-action-for-publishing-to-pypi" ]

permissions:
  contents: read

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Parse Main Branch Version
      run: echo MAIN_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
    - name: Checkout Feature Branch
      uses: actions/checkout@v4
    - name: Parse Feature Branch Version
      run: echo FEATURE_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
    - name: Check Bash Variables
      run: |
        if [ 5 > 4 ]
          then
            echo here
        fi
