name: "Verify Version Number"

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  verify_version_number:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Parse Main Branch Version
      run: echo MAIN_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
    - name: Checkout Feature Branch
      uses: actions/checkout@v4
    - name: Parse Feature Branch Version
      run: echo FEATURE_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
    - name: Check For Version Increment
      run: |
        if [ $MAIN_VER == $FEATURE_VER ]
        then
          echo "Feature branch version $FEATURE_VER must be greater than main branch version $MAIN_VER"
          false
        fi
        echo -e "$MAIN_VER\n$FEATURE_VER" | sort --version-sort --check