name: "Verify Version Number"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "33-create-a-github-action-for-publishing-to-pypi" ]

permissions:
  contents: read

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Branch
      uses: actions/checkout@v3
    - name: Get Current Branch Version
      uses: grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/'